# Generated by Django 5.0.3 on 2024-03-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('registration_date', models.DateField()),
                ('registration_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='donation',
            name='charity',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='session',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='charity',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='donation_amount',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='donation_method',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='usersession',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='stage',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Charity',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
