# Generated by Django 5.0.3 on 2024-03-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('donation_type', models.CharField(max_length=100)),
            ],
        ),
    ]
