# Generated by Django 5.0.3 on 2024-03-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0003_usersession_age_usersession_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='id_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
